<?php

namespace EasyCorp\Bundle\EasyAdminBundle\Tests\Unit\Skill\Support;

/**
 * Renders a Markdown reference of the EasyAdmin public API by reflecting on the
 * classes shipped in src/. AI coding agents read the generated file to check
 * whether a method exists before writing a call to it.
 */
final class ApiReferenceGenerator
{
    private const ROOT_NAMESPACE = 'EasyCorp\\Bundle\\EasyAdminBundle\\';
    private const HEADER = '<!-- Generated by "make skill-api-reference". Do not edit by hand. -->';
    private const MEMBERS_ALL = 'all';
    private const MEMBERS_CONSTANTS = 'constants';
    private const MEMBERS_CONSTRUCTOR = 'constructor';
    private const MEMBERS_PUBLIC = 'public';

    private string $packageDir;

    public function __construct(string $packageDir)
    {
        // paths are normalized to forward slashes so that the generated file is
        // identical on Windows and on Unix systems
        $this->packageDir = rtrim(str_replace('\\', '/', $packageDir), '/');
    }

    public function generate(): string
    {
        $classes = $this->classesInScope();

        $sections = [];
        $tableOfContents = [];
        foreach ($classes as $class => $scope) {
            $title = substr($class, \strlen(self::ROOT_NAMESPACE));
            $tableOfContents[] = sprintf('- [%s](#%s)', $title, $this->anchor($title));
            $sections[] = $this->renderClass($class, $title, $scope, $classes);
        }

        $lines = array_merge($this->renderIntroduction(), $tableOfContents, ['']);
        foreach ($sections as $section) {
            $lines = array_merge($lines, $section, ['']);
        }

        // the trailing empty item makes the file end with a single newline character
        array_pop($lines);

        return implode("\n", $lines)."\n";
    }

    /**
     * @return list<string>
     */
    private function renderIntroduction(): array
    {
        return [
            self::HEADER,
            '',
            '# EasyAdmin API Reference',
            '',
            'Public API of the installed EasyAdmin version, generated by reflection.',
            'If a method is not listed here, it does not exist.',
            '',
            'Every class below belongs to the `'.self::ROOT_NAMESPACE.'` namespace, which the',
            'section titles omit. Signatures use short class names and only list the members',
            'each class declares itself. A `self` return type means the call is chainable.',
            '',
            '## Table of contents',
            '',
        ];
    }

    /**
     * @param array<class-string, string> $allClasses
     *
     * @return list<string>
     */
    private function renderClass(string $class, string $title, string $scope, array $allClasses): array
    {
        $reflection = $this->reflect($class);

        $signatures = self::MEMBERS_CONSTRUCTOR === $scope
            ? $this->renderConstructor($reflection)
            : $this->renderMembers($reflection, $scope);

        $blocks = [];
        if ([] !== $signatures) {
            $blocks[] = array_merge(['```'], $signatures, ['```']);
        }

        foreach ($this->traitsInScope($reflection, $allClasses) as $trait) {
            $traitTitle = substr($trait, \strlen(self::ROOT_NAMESPACE));
            $blocks[] = [sprintf('Also accepts every %s method (see [%s](#%s)).', $this->shortName($trait), $traitTitle, $this->anchor($traitTitle))];
        }

        if ([] === $blocks) {
            $blocks[] = ['This class declares no members of its own.'];
        }

        $lines = ['## '.$title];
        foreach ($blocks as $block) {
            $lines[] = '';
            $lines = array_merge($lines, $block);
        }

        return $lines;
    }

    /**
     * @param \ReflectionClass<object> $reflection
     *
     * @return list<string>
     */
    private function renderConstructor(\ReflectionClass $reflection): array
    {
        $constructor = $reflection->getConstructor();
        if (null === $constructor || !$constructor->isPublic() || $this->isInternal($constructor->getDocComment())) {
            return [];
        }

        return ['__construct('.$this->renderParameters($constructor, $reflection->getName()).')'];
    }

    /**
     * @param \ReflectionClass<object> $reflection
     *
     * @return list<string>
     */
    private function renderMembers(\ReflectionClass $reflection, string $scope): array
    {
        $constants = $this->renderConstants($reflection);
        if (self::MEMBERS_CONSTANTS === $scope) {
            return $constants;
        }

        $class = $reflection->getName();
        $includeProtected = self::MEMBERS_ALL === $scope;
        $groups = [$constants, $this->renderProperties($reflection, $includeProtected)];

        $static = [];
        $instance = [];
        foreach ($reflection->getMethods() as $method) {
            if (!$this->isVisible($method, $includeProtected) || !$this->isOwnMethod($method, $reflection)) {
                continue;
            }

            if ($this->isInternal($method->getDocComment()) || $this->isSkippedMagicMethod($method)) {
                continue;
            }

            if ($method->isStatic()) {
                $static[$method->getName()] = $this->renderMethod($method, $class);
            } else {
                $instance[$method->getName()] = $this->renderMethod($method, $class);
            }
        }

        ksort($static, \SORT_STRING);
        ksort($instance, \SORT_STRING);
        $groups[] = array_values($static);
        $groups[] = array_values($instance);

        $lines = [];
        foreach ($groups as $group) {
            if ([] === $group) {
                continue;
            }

            if ([] !== $lines) {
                $lines[] = '';
            }

            $lines = array_merge($lines, $group);
        }

        return $lines;
    }

    /**
     * @param \ReflectionClass<object> $reflection
     *
     * @return list<string>
     */
    private function renderConstants(\ReflectionClass $reflection): array
    {
        $traitConstants = $this->traitConstantNames($reflection);

        $constants = [];
        foreach ($reflection->getReflectionConstants() as $constant) {
            if (!$constant->isPublic() || $constant->getDeclaringClass()->getName() !== $reflection->getName()) {
                continue;
            }

            if (isset($traitConstants[$constant->getName()]) || $this->isInternal($constant->getDocComment())) {
                continue;
            }

            $constants[$constant->getName()] = sprintf('const %s = %s', $constant->getName(), $this->exportValue($constant->getValue()));
        }

        ksort($constants, \SORT_STRING);

        return array_values($constants);
    }

    /**
     * @param \ReflectionClass<object> $reflection
     *
     * @return list<string>
     */
    private function renderProperties(\ReflectionClass $reflection, bool $includeProtected): array
    {
        $traitProperties = $this->traitPropertyNames($reflection);

        $properties = [];
        foreach ($reflection->getProperties() as $property) {
            if (!$this->isVisible($property, $includeProtected) || $property->getDeclaringClass()->getName() !== $reflection->getName()) {
                continue;
            }

            if (isset($traitProperties[$property->getName()]) || $this->isInternal($property->getDocComment())) {
                continue;
            }

            $signature = $property->isProtected() ? 'protected ' : '';
            $signature .= $property->isStatic() ? 'static ' : '';
            $type = $this->renderType($property->getType(), $property->getDeclaringClass()->getName());
            $signature .= '' === $type ? '' : $type.' ';

            $properties[$property->getName()] = $signature.'$'.$property->getName();
        }

        ksort($properties, \SORT_STRING);

        return array_values($properties);
    }

    private function renderMethod(\ReflectionMethod $method, string $class): string
    {
        $signature = $method->isProtected() ? 'protected ' : '';
        $signature .= $method->isStatic() ? 'static ' : '';
        $signature .= $method->getName().'('.$this->renderParameters($method, $class).')';

        $returnType = $this->renderType($method->getReturnType(), $class);

        return '' === $returnType ? $signature : $signature.': '.$returnType;
    }

    private function renderParameters(\ReflectionMethod $method, string $class): string
    {
        $parameters = [];
        foreach ($method->getParameters() as $parameter) {
            $rendered = $this->renderType($parameter->getType(), $class);
            $rendered = '' === $rendered ? '' : $rendered.' ';
            $rendered .= $parameter->isPassedByReference() ? '&' : '';
            $rendered .= $parameter->isVariadic() ? '...' : '';
            $rendered .= '$'.$parameter->getName();

            if (!$parameter->isVariadic() && $parameter->isDefaultValueAvailable()) {
                $rendered .= ' = '.$this->renderDefaultValue($parameter);
            }

            $parameters[] = $rendered;
        }

        return implode(', ', $parameters);
    }

    private function renderDefaultValue(\ReflectionParameter $parameter): string
    {
        if ($parameter->isDefaultValueConstant()) {
            $name = (string) $parameter->getDefaultValueConstantName();
            $separator = strrpos($name, '::');
            if (false === $separator) {
                return $name;
            }

            return $this->shortName(substr($name, 0, $separator)).substr($name, $separator);
        }

        return $this->exportValue($parameter->getDefaultValue());
    }

    private function exportValue(mixed $value): string
    {
        if (null === $value) {
            return 'null';
        }

        if (\is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (\is_int($value)) {
            return (string) $value;
        }

        if (\is_float($value)) {
            // formatted by hand because var_export() depends on the serialize_precision setting
            $formatted = rtrim(rtrim(sprintf('%.10F', $value), '0'), '.');

            return str_contains($formatted, '.') ? $formatted : $formatted.'.0';
        }

        if (\is_string($value)) {
            return "'".str_replace(['\\', "'"], ['\\\\', "\\'"], $value)."'";
        }

        if (\is_array($value)) {
            return $this->exportArray($value);
        }

        return '…';
    }

    /**
     * @param array<array-key, mixed> $value
     */
    private function exportArray(array $value): string
    {
        if ([] === $value) {
            return '[]';
        }

        $isList = array_is_list($value);
        $items = [];
        foreach ($value as $key => $item) {
            $items[] = $isList ? $this->exportValue($item) : $this->exportValue($key).' => '.$this->exportValue($item);
        }

        return '['.implode(', ', $items).']';
    }

    private function renderType(?\ReflectionType $type, string $class): string
    {
        // types are rendered by hand because the string representation of
        // ReflectionType is not identical in all the PHP versions this project supports
        if ($type instanceof \ReflectionNamedType) {
            // PHP resolves the 'self' type of class methods, but not the one of trait
            // methods, so it's turned back into 'self' to render both of them alike
            $name = $type->getName() === $class ? 'self' : $this->shortName($type->getName());
            $isNullable = $type->allowsNull() && !\in_array($name, ['mixed', 'null'], true);

            return $isNullable ? '?'.$name : $name;
        }

        if ($type instanceof \ReflectionIntersectionType) {
            return implode('&', $this->sortTypeNames($type->getTypes(), $class));
        }

        if ($type instanceof \ReflectionUnionType) {
            $names = $this->sortTypeNames($type->getTypes(), $class);

            // some PHP versions may decompose iterable into its two parts
            if (['Traversable', 'array'] === $names) {
                return 'iterable';
            }

            return implode('|', $names);
        }

        return '';
    }

    /**
     * @param list<\ReflectionType> $types
     *
     * @return list<string>
     */
    private function sortTypeNames(array $types, string $class): array
    {
        $names = [];
        foreach ($types as $type) {
            $name = $this->renderType($type, $class);
            $names[] = $type instanceof \ReflectionIntersectionType ? '('.$name.')' : $name;
        }

        sort($names, \SORT_STRING);

        // null reads better last and matches the PHPDoc convention of this project
        $nullPosition = array_search('null', $names, true);
        if (false !== $nullPosition) {
            unset($names[$nullPosition]);
            $names[] = 'null';
        }

        return array_values($names);
    }

    /**
     * @param \ReflectionClass<object>    $reflection
     * @param array<class-string, string> $allClasses
     *
     * @return list<class-string>
     */
    private function traitsInScope(\ReflectionClass $reflection, array $allClasses): array
    {
        $traits = [];
        foreach (array_keys($reflection->getTraits()) as $trait) {
            if (isset($allClasses[$trait])) {
                $traits[] = $trait;
            }
        }

        sort($traits, \SORT_STRING);

        return $traits;
    }

    /**
     * @param \ReflectionClass<object> $reflection
     *
     * @return array<string, true>
     */
    private function traitConstantNames(\ReflectionClass $reflection): array
    {
        $names = [];
        foreach ($reflection->getTraits() as $trait) {
            foreach (array_keys($trait->getConstants()) as $name) {
                $names[$name] = true;
            }

            $names += $this->traitConstantNames($trait);
        }

        return $names;
    }

    /**
     * @param \ReflectionClass<object> $reflection
     *
     * @return array<string, true>
     */
    private function traitPropertyNames(\ReflectionClass $reflection): array
    {
        $names = [];
        foreach ($reflection->getTraits() as $trait) {
            foreach ($trait->getProperties() as $property) {
                $names[$property->getName()] = true;
            }

            $names += $this->traitPropertyNames($trait);
        }

        return $names;
    }

    /**
     * @param \ReflectionClass<object> $reflection
     */
    private function isOwnMethod(\ReflectionMethod $method, \ReflectionClass $reflection): bool
    {
        if ($method->getDeclaringClass()->getName() !== $reflection->getName()) {
            return false;
        }

        // methods imported from a trait report the class using the trait as their
        // declaring class, so the file that defines them is what tells them apart
        return $method->getFileName() === $reflection->getFileName();
    }

    private function isVisible(\ReflectionMethod|\ReflectionProperty $member, bool $includeProtected): bool
    {
        return $member->isPublic() || ($includeProtected && $member->isProtected());
    }

    private function isSkippedMagicMethod(\ReflectionMethod $method): bool
    {
        return str_starts_with($method->getName(), '__');
    }

    private function isInternal(string|false|null $docComment): bool
    {
        return \is_string($docComment) && 1 === preg_match('/@internal\b/', $docComment);
    }

    private function shortName(string $name): string
    {
        $separator = strrpos($name, '\\');

        return false === $separator ? $name : substr($name, $separator + 1);
    }

    private function anchor(string $title): string
    {
        return (string) preg_replace('/[^a-z0-9-]/', '', strtolower($title));
    }

    /**
     * @return \ReflectionClass<object>
     */
    private function reflect(string $class): \ReflectionClass
    {
        try {
            return new \ReflectionClass($class);
        } catch (\ReflectionException|\Error $exception) {
            throw new \RuntimeException(sprintf('The class "%s" cannot be loaded, so the API reference cannot be generated. Its parent classes and interfaces must be autoloadable (e.g. PHPUnit must be installed to load the classes of the "src/Test/" directory). Error: %s', $class, $exception->getMessage()), 0, $exception);
        }
    }

    /**
     * @return array<class-string, string>
     */
    private function classesInScope(): array
    {
        $classes = [];
        foreach ($this->scopeDefinition() as [$directory, $pattern, $members]) {
            foreach ($this->findClasses($directory, $pattern) as $class) {
                if ($this->isInternal($this->reflect($class)->getDocComment())) {
                    continue;
                }

                $classes[$class] = $members;
            }
        }

        ksort($classes, \SORT_STRING);

        return $classes;
    }

    /**
     * @return list<array{string, string, string}>
     */
    private function scopeDefinition(): array
    {
        return [
            ['Attribute', '*.php', self::MEMBERS_CONSTRUCTOR],
            ['Config', '*.php', self::MEMBERS_PUBLIC],
            ['Config/Menu', '*.php', self::MEMBERS_PUBLIC],
            ['Config/Option', '*.php', self::MEMBERS_CONSTANTS],
            ['Contracts/Controller', '*.php', self::MEMBERS_PUBLIC],
            ['Controller', 'Abstract*.php', self::MEMBERS_ALL],
            ['Field', '*.php', self::MEMBERS_PUBLIC],
            ['Filter', '*.php', self::MEMBERS_PUBLIC],
            ['Router', 'AdminUrlGenerator.php', self::MEMBERS_PUBLIC],
            ['Test', '*.php', self::MEMBERS_ALL],
            ['Test/Trait', '*.php', self::MEMBERS_ALL],
        ];
    }

    /**
     * @return list<class-string>
     */
    private function findClasses(string $directory, string $pattern): array
    {
        $files = glob($this->packageDir.'/src/'.$directory.'/'.$pattern);
        if (false === $files) {
            throw new \RuntimeException(sprintf('The "%s/src/%s/" directory of the EasyAdmin package cannot be read.', $this->packageDir, $directory));
        }

        // glob() does not guarantee any order, so the file names are sorted explicitly
        sort($files, \SORT_STRING);

        $namespace = self::ROOT_NAMESPACE.str_replace('/', '\\', $directory).'\\';
        $classes = [];
        foreach ($files as $file) {
            $classes[] = $namespace.basename($file, '.php');
        }

        return $classes;
    }
}
