<?php

namespace EasyCorp\Bundle\EasyAdminBundle\EventListener;

use EasyCorp\Bundle\EasyAdminBundle\Config\Option\CacheKey;
use EasyCorp\Bundle\EasyAdminBundle\Config\Option\EA;
use EasyCorp\Bundle\EasyAdminBundle\Contracts\Controller\DashboardControllerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Contracts\Router\AdminRouteGeneratorInterface;
use EasyCorp\Bundle\EasyAdminBundle\Exception\BaseException;
use EasyCorp\Bundle\EasyAdminBundle\Factory\AdminContextFactory;
use EasyCorp\Bundle\EasyAdminBundle\Factory\ControllerFactory;
use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Controller\ControllerResolverInterface;
use Symfony\Component\HttpKernel\Event\ControllerEvent;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Exception\InvalidParameterException;
use Symfony\Component\Routing\Exception\MethodNotAllowedException;
use Symfony\Component\Routing\Exception\MissingMandatoryParametersException;
use Symfony\Component\Routing\Exception\ResourceNotFoundException;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\Matcher\RequestMatcherInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Http\AccessMapInterface;

/**
 * This subscriber acts as a "proxy" of all backend requests. First, if the
 * request is related to EasyAdmin, it creates the AdminContext variable and
 * stores it in the Request as an attribute.
 *
 * Second, it uses Symfony events to serve all backend requests using a single
 * route. The trick is to change dynamically the controller to execute when
 * the request is related to a CRUD action or a normal Symfony route/action.
 *
 * @author Javier Eguiluz <javier.eguiluz@gmail.com>
 * @author Maxime Steinhausser <maxime.steinhausser@gmail.com>
 * @author Yonel Ceruto <yonelceruto@gmail.com>
 */
readonly class AdminRouterSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private AdminContextFactory $adminContextFactory,
        private ControllerFactory $controllerFactory,
        private ControllerResolverInterface $controllerResolver,
        private UrlGeneratorInterface $urlGenerator,
        private RequestMatcherInterface $requestMatcher,
        private CacheItemPoolInterface $cache,
        private AdminRouteGeneratorInterface $adminRouteGenerator,
        private ?AccessMapInterface $accessMap = null,
        private ?AuthorizationCheckerInterface $authorizationChecker = null,
    ) {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            RequestEvent::class => [
                ['onKernelRequest', 1],
            ],
            // the priority must be higher than 0 to run it before ParamConverterListener
            ControllerEvent::class => ['onKernelController', 128],
        ];
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        if (false === $request->attributes->getBoolean(EA::ROUTE_CREATED_BY_EASYADMIN)) {
            return;
        }

        // edge-case: in some scenarios, admin routes are generated by the custom route loader
        // and their information is cached but then removed from the cache (e.g. when running
        // 'rm -fr var/cache/* && bin/console cache:clear'). If that's the case, regenerate the
        // admin routes to force saving them in the cache again.
        // see https://github.com/EasyCorp/EasyAdminBundle/issues/6680
        $adminRoutes = $this->cache->getItem(CacheKey::ROUTE_NAME_TO_ATTRIBUTES)->get();
        if (null === $adminRoutes) {
            $this->adminRouteGenerator->generateAll();
        }

        $dashboardControllerFqcn = $request->attributes->get(EA::DASHBOARD_CONTROLLER_FQCN);
        if (null === $dashboardControllerInstance = $this->getDashboardControllerInstance($dashboardControllerFqcn, $request)) {
            return;
        }

        // creating the context is expensive, so it's created once and stored in the request
        // if the current request already has an AdminContext object, do nothing
        if (null === $adminContext = $request->attributes->get(EA::CONTEXT_REQUEST_ATTRIBUTE)) {
            $crudControllerFqcn = $request->attributes->get(EA::CRUD_CONTROLLER_FQCN);
            $actionName = $request->attributes->get(EA::CRUD_ACTION);

            $crudControllerInstance = $this->controllerFactory->getCrudControllerInstance($crudControllerFqcn, $actionName, $request);

            try {
                $adminContext = $this->adminContextFactory->create($request, $dashboardControllerInstance, $crudControllerInstance, $actionName);
            } catch (BaseException $e) {
                // if context creation fails (e.g. entity not found), create a context
                // without the entity so the ExceptionListener can still render the
                // EasyAdmin error page with the proper layout. To prevent the entity from
                // being loaded again, the entity ID must be removed from everywhere it can be
                // read from: the canonical 'entityId' attribute, its 'id' alias, and the matched
                // '_route_params' (used for mapped route placeholders). Only the values that
                // originally existed are restored afterwards, so the exception message stays accurate
                // and no attribute that wasn't present before is introduced.
                $hadEntityIdAttribute = $request->attributes->has(EA::ENTITY_ID);
                $hadIdAttribute = $request->attributes->has('id');
                $hadRouteParams = $request->attributes->has('_route_params');
                $entityIdAttribute = $request->attributes->get(EA::ENTITY_ID);
                $idAttribute = $request->attributes->get('id');
                $routeParams = $request->attributes->get('_route_params', []);

                $request->attributes->remove(EA::ENTITY_ID);
                $request->attributes->remove('id');
                $request->query->remove(EA::ENTITY_ID);
                if ($hadRouteParams) {
                    $cleanedRouteParams = $routeParams;
                    unset($cleanedRouteParams[EA::ENTITY_ID], $cleanedRouteParams['id']);
                    $request->attributes->set('_route_params', $cleanedRouteParams);
                }

                try {
                    $adminContext = $this->adminContextFactory->create($request, $dashboardControllerInstance, $crudControllerInstance, $actionName);
                    $request->attributes->set(EA::CONTEXT_REQUEST_ATTRIBUTE, $adminContext);
                } catch (\Throwable) {
                    // creating the fallback context runs user-defined code (e.g. configureActions())
                    // against a context without an entity, so it may fail too; ignore that second
                    // error because the original exception is more useful (the error page will
                    // simply be rendered without the EasyAdmin layout)
                } finally {
                    // restore the original request data so the exception message is accurate
                    if ($hadEntityIdAttribute) {
                        $request->attributes->set(EA::ENTITY_ID, $entityIdAttribute);
                    }
                    if ($hadIdAttribute) {
                        $request->attributes->set('id', $idAttribute);
                    }
                    if ($hadRouteParams) {
                        $request->attributes->set('_route_params', $routeParams);
                    }
                }

                throw $e;
            }
        }

        $request->attributes->set(EA::CONTEXT_REQUEST_ATTRIBUTE, $adminContext);
    }

    /**
     * In EasyAdmin all backend requests are served via the same route (that allows to
     * detect under which dashboard you want to process the request). This method handles
     * the requests related to "CRUD controller actions" and "custom Symfony actions".
     * The trick used is to change dynamically the controller executed by Symfony.
     */
    public function onKernelController(ControllerEvent $event): void
    {
        $request = $event->getRequest();
        if (null === $request->attributes->get(EA::CONTEXT_REQUEST_ATTRIBUTE)) {
            return;
        }

        // if the request is related to a custom action, change the controller to be executed
        if (null !== $request->query->get(EA::ROUTE_NAME)) {
            $symfonyControllerAsString = $this->getSymfonyControllerFqcn($request);
            $symfonyControllerCallable = $this->getSymfonyControllerInstance($symfonyControllerAsString, $request->query->all(EA::ROUTE_PARAMS));
            if (false !== $symfonyControllerCallable) {
                // this makes Symfony believe that another controller is being executed
                // (e.g. this is needed for the autowiring of controller action arguments)
                // VERY IMPORTANT: here the Symfony controller must be passed as a string ('App\Controller\Foo::index')
                // Otherwise, the param converter of the controller method doesn't work
                $event->getRequest()->attributes->set('_controller', $symfonyControllerAsString);
                // route params must be added as route attribute; otherwise, param converters don't work
                $event->getRequest()->attributes->replace(array_merge(
                    $request->query->all(EA::ROUTE_PARAMS),
                    $event->getRequest()->attributes->all()
                ));

                // this actually makes Symfony to execute the other controller
                $event->setController($symfonyControllerCallable);
            }
        }
    }

    private function getDashboardControllerInstance(string $dashboardControllerFqcn, Request $request): ?DashboardControllerInterface
    {
        return $this->controllerFactory->getDashboardControllerInstance($dashboardControllerFqcn, $request);
    }

    private function getSymfonyControllerFqcn(Request $request): ?string
    {
        $routeName = $request->query->get(EA::ROUTE_NAME);
        $routeParams = $request->query->all(EA::ROUTE_PARAMS);

        try {
            $url = $this->urlGenerator->generate($routeName, $routeParams, UrlGeneratorInterface::ABSOLUTE_PATH);
        } catch (RouteNotFoundException $e) {
            // 'routeName' and 'routeParams' come from the query string, so a
            // typo (or a bot probing legacy ?routeName= URLs) is a client
            // error: return a 404 instead of an uncaught 500 (#7827)
            throw new NotFoundHttpException(sprintf('The route "%s" does not exist.', $routeName), $e);
        } catch (MissingMandatoryParametersException $e) {
            throw new NotFoundHttpException(sprintf('The route "%s" cannot be generated because some mandatory parameters are missing.', $routeName), $e);
        } catch (InvalidParameterException $e) {
            throw new NotFoundHttpException(sprintf('The parameters provided for the route "%s" are not valid.', $routeName), $e);
        }

        $newRequest = $request->duplicate();
        $newRequest->attributes->remove('_controller');
        $newRequest->attributes->set('_route', $routeName);
        $newRequest->attributes->add($routeParams);

        // If the application is running behind a proxy under a permanent
        // subpath prefix (AKA sub-folder, sub-url or sub-path) using the HTTP
        // header x-forwarded-prefix, the URL is generated with
        // that prefix. We need to remove it before we can match it.
        $basePath = $request->getBasePath();
        if ('' !== $request->getBasePath() && str_starts_with($url, $basePath)) {
            $url = mb_substr($url, mb_strlen($basePath));
        }

        $newRequest->server->set('REQUEST_URI', $url);

        $this->assertTargetRouteAccessIsGranted($newRequest);

        try {
            $parameters = $this->requestMatcher->matchRequest($newRequest);
        } catch (MethodNotAllowedException $e) {
            throw new MethodNotAllowedHttpException($e->getAllowedMethods(), sprintf('The route "%s" does not allow the "%s" method (allowed methods: %s).', $routeName, $newRequest->getMethod(), implode(', ', $e->getAllowedMethods())), $e);
        } catch (ResourceNotFoundException $e) {
            throw new NotFoundHttpException(sprintf('The route "%s" does not match the current request (check its host, scheme and condition).', $routeName), $e);
        }

        return $parameters['_controller'] ?? null;
    }

    /**
     * The controller of a custom action (?routeName=...) is swapped in on the
     * 'kernel.controller' event, which runs *after* Symfony's security firewall has
     * already evaluated 'access_control' against the original admin URL. Without this
     * check, any path-based access_control rule protecting the *target* route would be
     * silently skipped, allowing it to be reached through EasyAdmin. So we re-evaluate
     * that rule here against the target request.
     *
     * This mirrors Symfony's own AccessListener, but evaluates the matched attributes one
     * by one through the authorization checker instead of calling the access decision
     * manager directly: the signature of AccessDecisionManagerInterface::decide() (needed
     * to pass several attributes at once) is not portable across the Symfony versions this
     * bundle supports.
     */
    private function assertTargetRouteAccessIsGranted(Request $request): void
    {
        if (null === $this->accessMap || null === $this->authorizationChecker) {
            return;
        }

        [$attributes] = $this->accessMap->getPatterns($request);

        if (null === $attributes || [] === $attributes || [AuthenticatedVoter::PUBLIC_ACCESS] === $attributes) {
            return;
        }

        foreach ($attributes as $attribute) {
            if ($this->authorizationChecker->isGranted($attribute)) {
                return;
            }
        }

        throw new AccessDeniedException(sprintf('Access to the "%s" route is denied by an access control rule; it cannot be reached through an EasyAdmin custom action.', $request->attributes->get('_route')));
    }

    /**
     * @param array<string, mixed> $routeParams
     */
    private function getSymfonyControllerInstance(string $controllerFqcn, array $routeParams): callable|false
    {
        $newRequest = new Request([], [], ['_controller' => $controllerFqcn, '_route_params' => $routeParams], [], [], []);

        return $this->controllerResolver->getController($newRequest);
    }
}
