<?php

/*
 * This file is part of the EasyAdminBundle.
 *
 * (c) Javier Eguiluz <javier.eguiluz@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace JavierEguiluz\Bundle\EasyAdminBundle\DependencyInjection;

use Symfony\Component\HttpKernel\DependencyInjection\Extension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\Config\FileLocator;

class EasyAdminExtension extends Extension
{
    private $defaultBundleConfiguration = array(
        'site_name' => 'EasyAdmin',
        'list_max_results' => 15,
        'list_actions' => array('edit'),
        'entities' => array(),
    );

    private $defaultFieldConfiguration = array(
        'class'  => null,
        'help'   => null,
        'label'  => null,
        'type'   => null,
        'format' => null,
    );

    public function load(array $configs, ContainerBuilder $container)
    {
        // process bundle's configuration parameters
        $bundleConfiguration = $this->processConfiguration(new Configuration(), $configs);

        $backendConfiguration = array_replace($this->defaultBundleConfiguration, $bundleConfiguration);
        $backendConfiguration['entities'] = $this->getEntitiesConfiguration($backendConfiguration['entities']);

        $container->setParameter('easyadmin.config', $backendConfiguration);

        // load bundle's services
        $loader = new XmlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.xml');
    }

    /**
     * Processes, normalizes and initializes the configuration of the entities
     * that are managed by the backend. Several configuration formats are allowed,
     * so this method normalizes them all.
     *
     * @param  array $entitiesConfiguration
     * @return array The full entity configuration
     */
    protected function getEntitiesConfiguration(array $entitiesConfiguration)
    {
        if (0 === count($entitiesConfiguration)) {
            return $entitiesConfiguration;
        }

        // if the entity configuration uses the shortcut syntax, normalize it before processing it
        $entitiesConfigurationValues = array_values($entitiesConfiguration);
        if (is_string($entitiesConfigurationValues[0])) {
            $entitiesConfiguration = $this->normalizeEntityConfiguration($entitiesConfiguration);
        }

        return $this->processEntitiesConfiguration($entitiesConfiguration);
    }

    /**
     * Transforms the two simple configuration formats into the full expanded
     * configuration. This allows to reuse the same method to process any of the
     * different configuration formats.
     *
     * These are the two simple formats allowed:
     *
     * # simple config with no custom entity label
     * easy_admin:
     *     entities:
     *         - AppBundle\Entity\User
     *
     * # simple config with custom entity label
     * easy_admin:
     *     entities:
     *         User: AppBundle\Entity\User
     *
     * And this is the full expanded configuration syntax generated by this method:
     *
     * easy_admin:
     *     entities:
     *         User:
     *             class: AppBundle\Entity\User
     *
     * @param  array $simpleConfig The entity configuration in one of the simplified formats
     * @return array The normalized configuration
     */
    private function normalizeEntityConfiguration(array $simpleConfig)
    {
        $normalizedConfig = array();

        $entityNames = array();
        foreach ($simpleConfig as $entityName => $entityClass) {
            if (is_integer($entityName)) {
                // the simplest configuration format defines no custom entity names,
                // so let's use the name of the entity class as its name
                $entityClassParts = explode('\\', $entityClass);
                $entityName = array_pop($entityClassParts);
            }

            $uniqueEntityName = $this->getUniqueEntityName($entityClass, $entityNames);
            $entityNames[] = $uniqueEntityName;

            $normalizedConfig[$uniqueEntityName] = array(
                'class' => $entityClass,
            );
        }

        return $normalizedConfig;
    }

    /**
     * Normalizes and initializes the configuration of the given entities to
     * simplify the option processing of the other methods and functions.
     *
     * @param  array $entitiesConfiguration
     * @return array The configured entities
     */
    private function processEntitiesConfiguration(array $entitiesConfiguration)
    {
        $entities = array();

        $entityNames = array();
        foreach ($entitiesConfiguration as $entityName => $entityConfiguration) {
            // copy the original entity configuration to not loose any of its options
            $config = $entityConfiguration;

            // basic entity configuration
            $config['label'] = $entityName;
            $config['class'] = $entityConfiguration['class'];

            $config['actions'] = isset($entityConfiguration['actions']) ? $entityConfiguration['actions'] : [];

            // configuration for the actions related to the entity ('list', 'edit', etc.)
            foreach (array('edit', 'form', 'list', 'new', 'show') as $action) {
                // if needed, initialize options to simplify further configuration processing
                if (!array_key_exists($action, $config)) {
                    $config[$action] = array('fields' => array());
                }
                if (!array_key_exists('fields', $config[$action])) {
                    $config[$action]['fields'] = array();
                }

                $config[$action]['fields'] = $this->processFieldsConfiguration($config[$action]['fields'], $action, $config['class']);
            }

            $uniqueEntityName = $this->getUniqueEntityName($config['class'], $entityNames);
            $entityNames[] = $uniqueEntityName;

            $config['name']  = $uniqueEntityName;

            $entities[$uniqueEntityName] = $config;
        }

        return $entities;
    }

    /**
     * The name of the entity is used in the URLs of the application to define the
     * entity which should be used for each action. Obviously, the entity name
     * must be unique in the application.
     *
     * To avoid entity name conflicts when two different entities are called the
     * same, this method modifies the entity name if necessary to ensure that is
     * unique.
     *
     * @param  string $entityClass
     * @param  array  $entityNames The list of names of all the managed entities
     * @return string The name of the entity guaranteed to be unique in the application
     */
    private function getUniqueEntityName($entityClass, $entityNames)
    {
        $entityClassParts = explode('\\', $entityClass);
        $uniqueEntityName = array_pop($entityClassParts);

        while (in_array($uniqueEntityName, $entityNames)) {
            $uniqueEntityName .= '_';
        }

        return $uniqueEntityName;
    }

    /**
     * Actions can define their fields using two different formats:
     *
     * # simple configuration
     * easy_admin:
     *     Client:
     *         # ...
     *         list:
     *             fields: ['id', 'name', 'email']
     *
     * # extended configuration
     * easy_admin:
     *     Client:
     *         # ...
     *         list:
     *             fields: ['id', 'name', { property: 'email', label: 'Contact' }]
     *
     * This method processes both formats to produce a common form field configuration
     * format. It also initializes and adds some default form field options to simplify
     * field configuration processing in other methods and templates.
     *
     * @param  array  $fieldsConfiguration
     * @param  string $action
     * @param  string $entityClass
     * @return array  The configured entity fields
     */
    private function processFieldsConfiguration(array $fieldsConfiguration, $action, $entityClass)
    {
        $fields = array();

        foreach ($fieldsConfiguration as $field) {
            // simple configuration: field is just a string representing the entity property
            if (is_string($field)) {
                $fieldConfiguration = array(
                    'property' => $field,
                );
            // extended configuration: field is an array that defines one or more options.
            // related entity property is configured via the mandatory 'property' option.
            } elseif (is_array($field)) {
                if (!array_key_exists('property', $field)) {
                    throw new \RuntimeException(sprintf('One of the values of the "fields" option for the "%s" action of the "%s" entity does not define the "property" option.', $action, $entityClass));
                }

                $fieldConfiguration = $field;
            } else {
                throw new \RuntimeException(sprintf('The values of the "fields" option for the "$s" action of the "%s" entity can only be strings or arrays.', $action, $entityClass));
            }

            $fieldConfiguration = array_replace($this->defaultFieldConfiguration, $fieldConfiguration);

            $fieldName = $fieldConfiguration['property'];
            $fields[$fieldName] = $fieldConfiguration;
        }

        return $fields;
    }
}
