<?php

/*
 * This file is part of the EasyAdminBundle.
 *
 * (c) Javier Eguiluz <javier.eguiluz@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace JavierEguiluz\Bundle\EasyAdminBundle\DependencyInjection;

use Symfony\Component\HttpKernel\DependencyInjection\Extension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\Config\FileLocator;

class EasyAdminExtension extends Extension
{
    private $defaultConfigOptions = array(
        'site_name' => 'ACME',
        'list_max_results' => 15,
        'list_actions' => array('edit'),
        'entities' => array(),
    );

    public function load(array $configs, ContainerBuilder $container)
    {
        // process configuration parameters
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $options = array_replace($this->defaultConfigOptions, $config);
        $options['entities'] = $this->getEntityConfiguration($options['entities']);

        $container->setParameter('easy_admin.config', $options);

        // load bundle's services
        $loader = new XmlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.xml');
    }

    protected function getEntityConfiguration(array $entitiesConfiguration)
    {
        if (0 === count($entitiesConfiguration)) {
            return $entitiesConfiguration;
        }

        $entitiesConfigurationValues = array_values($entitiesConfiguration);
        if (is_string($entitiesConfigurationValues[0])) {
            $entitiesConfiguration = $this->normalizeEntityConfiguration($entitiesConfiguration);
        }

        return $this->processEntityConfiguration($entitiesConfiguration);
    }

    /**
     * Transforms the two shortcut configuration formats into the full expanded
     * configuration. This allows to reuse the same method to process any of the
     * three different configuration formats.
     *
     * These are the two shortcut formats allowed:
     *
     * # simple config with no custom entity label
     * easy_admin:
     *     entities:
     *         - AppBundle\Entity\User
     *
     * # simple config with custom entiy label
     * easy_admin:
     *     entities:
     *         User: AppBundle\Entity\User
     *
     * And this is the full expanded configuration syntax generated by this method:
     *
     * easy_admin:
     *     entities:
     *         User:
     *             class: AppBundle\Entity\User
     */
    private function normalizeEntityConfiguration(array $config)
    {
        $normalizedConfig = array();
        foreach ($config as $entityName => $entityClass) {
            // the simplest configuration format defines no custom entity names,
            // so let's use the name of the entity class as its name
            if (is_integer($entityName)) {
                $parts = explode('\\', $entityClass);
                $entityName = array_pop($parts);
            }

            $normalizedConfig[$entityName] = array(
                'class' => $entityClass,
            );
        }

        return $normalizedConfig;
    }

    private function processEntityConfiguration(array $config)
    {
        $entities = array();
        foreach ($config as $customEntityName => $entityConfiguration) {
            $parts = explode('\\', $entityConfiguration['class']);
            $realEntityName = array_pop($parts);

            // to avoid entity name collision, make sure that its name is unique
            while (array_key_exists($realEntityName, $entities)) {
                $realEntityName .= '_';
            }

            // copy the original entity to not loose any of its configuration
            $entities[$realEntityName] = $config[$customEntityName];

            // process the original configuration to use the format needed by the application
            $entities[$realEntityName]['label'] = $customEntityName;
            $entities[$realEntityName]['name']  = $realEntityName;
            $entities[$realEntityName]['class'] = $entityConfiguration['class'];
        }

        return $entities;
    }
}
