<?php

namespace EasyCorp\Bundle\EasyAdminBundle\Tests\Functional\Fields\Special;

use EasyCorp\Bundle\EasyAdminBundle\Tests\Functional\AbstractFieldFunctionalTest;
use Symfony\Component\DomCrawler\Crawler;

class IdFieldTest extends AbstractFieldFunctionalTest
{
    public function testIdFieldDisplaysOnIndex(): void
    {
        $entity = $this->createFieldTestEntity([
            'textField' => 'Test for ID',
        ]);

        $crawler = $this->client->request('GET', $this->generateIndexUrlSortedByIdDesc());

        $entityRow = $crawler->filter(sprintf('tr[data-id="%d"]', $entity->getId()));
        static::assertCount(1, $entityRow, 'Entity row should exist');

        // idField should be displayed on index
        $idFieldCell = $entityRow->filter('td[data-column="id"]');
        static::assertCount(1, $idFieldCell, 'ID field cell should exist');
        static::assertStringContainsString((string) $entity->getId(), $idFieldCell->text());
    }

    public function testIdFieldDisplaysOnDetail(): void
    {
        $entity = $this->createFieldTestEntity([
            'textField' => 'Test for ID detail',
        ]);

        $crawler = $this->client->request('GET', $this->generateDetailUrl($entity->getId()));

        $fieldGroups = $crawler->filter('.content-body .field-group');
        $idFieldFound = false;

        foreach ($fieldGroups as $fieldGroup) {
            $groupCrawler = new Crawler($fieldGroup);
            $label = $groupCrawler->filter('.field-label')->text();

            if (false !== stripos($label, 'Id') || false !== stripos($label, 'ID')) {
                $idFieldFound = true;
                $fieldValue = $groupCrawler->filter('.field-value')->text();
                static::assertStringContainsString((string) $entity->getId(), $fieldValue);
                break;
            }
        }

        static::assertTrue($idFieldFound, 'IdField should be displayed on detail page');
    }

    public function testIdFieldNotDisplayedOnNewForm(): void
    {
        $crawler = $this->client->request('GET', $this->generateNewFormUrl());

        $form = $crawler->filter('form[name="FieldTestEntity"]');
        static::assertCount(1, $form, 'Form should exist');

        // idField is typically hidden on forms (hideOnForm)
        $idFieldInput = $crawler->filter('#FieldTestEntity_id');
        static::assertCount(0, $idFieldInput, 'IdField input should not exist in new form');
    }

    public function testIdFieldNotDisplayedOnEditForm(): void
    {
        $entity = $this->createFieldTestEntity([
            'textField' => 'Test for ID edit',
            'slugField' => 'id-edit-test',
        ]);

        $crawler = $this->client->request('GET', $this->generateEditFormUrl($entity->getId()));

        // idField should not be editable
        $idFieldInput = $crawler->filter('#FieldTestEntity_id');
        static::assertCount(0, $idFieldInput, 'IdField input should not exist in edit form');
    }

    public function testIdFieldIsAutoGenerated(): void
    {
        $entity1 = $this->createFieldTestEntity(['textField' => 'First']);
        $entity2 = $this->createFieldTestEntity(['textField' => 'Second']);

        static::assertNotNull($entity1->getId());
        static::assertNotNull($entity2->getId());
        static::assertNotSame($entity1->getId(), $entity2->getId());
        static::assertGreaterThan($entity1->getId(), $entity2->getId());
    }

    public function testIdFieldDisplaysCorrectValueOnIndex(): void
    {
        // create multiple entities
        $entities = [];
        for ($i = 0; $i < 3; ++$i) {
            $entities[] = $this->createFieldTestEntity([
                'textField' => 'Entity '.$i,
            ]);
        }

        $crawler = $this->client->request('GET', $this->generateIndexUrlSortedByIdDesc());

        // verify each entity's ID is displayed correctly
        foreach ($entities as $entity) {
            $entityRow = $crawler->filter(sprintf('tr[data-id="%d"]', $entity->getId()));
            static::assertCount(1, $entityRow, sprintf('Entity row for ID %d should exist', $entity->getId()));

            $idFieldCell = $entityRow->filter('td[data-column="id"]');
            static::assertStringContainsString((string) $entity->getId(), $idFieldCell->text());
        }
    }

    public function testIdFieldUsedInRowDataAttribute(): void
    {
        $entity = $this->createFieldTestEntity([
            'textField' => 'Test data attribute',
        ]);

        $crawler = $this->client->request('GET', $this->generateIndexUrlSortedByIdDesc());

        // the row should have data-id attribute with the entity ID
        $entityRow = $crawler->filter(sprintf('tr[data-id="%d"]', $entity->getId()));
        static::assertCount(1, $entityRow);
        static::assertSame((string) $entity->getId(), $entityRow->attr('data-id'));
    }

    public function testIdFieldInUrlGeneration(): void
    {
        $entity = $this->createFieldTestEntity([
            'textField' => 'Test URL generation',
        ]);

        $detailUrl = $this->generateDetailUrl($entity->getId());
        static::assertStringContainsString((string) $entity->getId(), $detailUrl);

        $editUrl = $this->generateEditFormUrl($entity->getId());
        static::assertStringContainsString((string) $entity->getId(), $editUrl);
    }
}
