#!/bin/bash

echo 'Deprecation notice: The "ddev build-assets" command is deprecated'
echo 'Please use "ddev make build" and "ddev make build-assets" instead'
echo ""

cd ../easyadminbundle
make build
make build-assets
