#!/bin/bash

# Installing Symfony Framework
composer create-project symfony/skeleton:"7.1.*" -n
mv -f ./skeleton/* ./
mv -f ./skeleton/.env ./
mv -f ./skeleton/.gitignore ./
rmdir ./skeleton

# Add local EasyAdminBundle sources as path repository and update project
composer config repositories.easyadminbundle path ../easyadminbundle
composer config extra.symfony.allow-contrib true
composer require "easycorp/easyadmin-bundle": "*@dev" symfony/apache-pack -n
composer require debug -n --dev

# Copy example entities, form and controllers
mkdir src/Form/
cp -r ../easyadminbundle/.ddev/example/Entity/* src/Entity/
cp -r ../easyadminbundle/.ddev/example/Controller/* src/Controller/
cp -r ../easyadminbundle/.ddev/example/Form/* src/Form/

# Initialize DB
echo 'DATABASE_URL="mysql://db:db@db:3306/db?serverVersion=10.4.0-MariaDB&charset=utf8mb4"' >> .env.local
./bin/console doc:sch:up --force
