# OS: Linux; Symfony: lowest supported by this bundle; PHP: lowest supported by this bundle
name: "Tests - Lowest supported dependencies"

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    fail-fast: true

jobs:
    tests:
        runs-on: 'ubuntu-latest'
        continue-on-error: false
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2.3.3

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: '7.2.5'
                  tools: composer:v2
                  extensions: mbstring, intl, pdo, pdo_sqlite, sqlite3
                  ini-values: date.timezone=UTC

            - name: 'Install project dependencies'
              run: |
                  composer global require --no-progress --no-scripts --no-plugins symfony/flex
                  composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable --prefer-lowest
                  vendor/bin/simple-phpunit install

            - name: 'Run tests'
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=10&max[total]=27'
              run: vendor/bin/simple-phpunit -v
